package ai

import (
	"encoding/base64"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// clearImageEnv sandboxes HOME and blanks every setting the image path reads.
func clearImageEnv(t *testing.T) {
	t.Helper()
	t.Setenv("HOME", t.TempDir())
	for _, k := range []string{
		"IMAGE_BASE_URL", "IMAGE_API_KEY", "IMAGE_MODEL",
		"ATLAS_API_KEY", "OPENAI_API_KEY",
	} {
		t.Setenv(k, "")
	}
}

// pngBytes is a minimal valid PNG header, enough for content sniffing.
var pngBytes = []byte("\x89PNG\r\n\x1a\n0123456789")

func TestGenerateImageOpenAIBase64(t *testing.T) {
	clearImageEnv(t)

	var gotPath, gotAuth string
	var gotBody map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		json.NewDecoder(r.Body).Decode(&gotBody)
		json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]string{{"b64_json": base64.StdEncoding.EncodeToString(pngBytes)}},
		})
	}))
	defer srv.Close()

	t.Setenv("IMAGE_BASE_URL", srv.URL+"/api/v1/") // trailing slash must not double up
	t.Setenv("IMAGE_API_KEY", "lemonade-key")
	t.Setenv("IMAGE_MODEL", "sdxl-turbo")

	url, err := GenerateImage("a lighthouse at dusk")
	if err != nil {
		t.Fatalf("GenerateImage: %v", err)
	}
	if gotPath != "/api/v1/images/generations" {
		t.Errorf("request path = %q, want /api/v1/images/generations", gotPath)
	}
	if gotAuth != "Bearer lemonade-key" {
		t.Errorf("Authorization = %q, want Bearer lemonade-key", gotAuth)
	}
	if gotBody["model"] != "sdxl-turbo" || gotBody["prompt"] != "a lighthouse at dusk" {
		t.Errorf("request body = %v", gotBody)
	}
	if !strings.HasPrefix(url, "/images/file/") || !strings.HasSuffix(url, ".png") {
		t.Fatalf("url = %q, want /images/file/<name>.png", url)
	}

	name := strings.TrimPrefix(url, "/images/file/")
	stored, err := os.ReadFile(filepath.Join(os.Getenv("HOME"), ".mu", "data", "images", "generated", name))
	if err != nil {
		t.Fatalf("stored image unreadable: %v", err)
	}
	if string(stored) != string(pngBytes) {
		t.Error("stored image bytes differ from generated bytes")
	}
}

func TestGenerateImageOpenAIHostedURL(t *testing.T) {
	clearImageEnv(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]string{{"url": "https://cdn.example.com/img.png"}},
		})
	}))
	defer srv.Close()
	t.Setenv("IMAGE_BASE_URL", srv.URL)

	url, err := GenerateImage("a lighthouse at dusk")
	if err != nil {
		t.Fatalf("GenerateImage: %v", err)
	}
	if url != "https://cdn.example.com/img.png" {
		t.Errorf("url = %q, want the hosted URL returned verbatim", url)
	}
}

// The image endpoint is more specific than the general Atlas key, so it must
// win when both are configured — and no model default may leak into the body:
// unnamed models are the local server's own choice.
func TestGenerateImageEndpointBeatsAtlasAndOmitsModel(t *testing.T) {
	clearImageEnv(t)

	var gotBody map[string]any
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		json.NewDecoder(r.Body).Decode(&gotBody)
		json.NewEncoder(w).Encode(map[string]any{
			"data": []map[string]string{{"url": "https://cdn.example.com/img.png"}},
		})
	}))
	defer srv.Close()

	t.Setenv("IMAGE_BASE_URL", srv.URL)
	t.Setenv("ATLAS_API_KEY", "atlas-key") // would 404 against the test server's atlas paths

	if _, err := GenerateImage("a lighthouse at dusk"); err != nil {
		t.Fatalf("GenerateImage: %v", err)
	}
	if gotBody == nil {
		t.Fatal("image endpoint was not called despite IMAGE_BASE_URL being set")
	}
	if _, ok := gotBody["model"]; ok {
		t.Errorf("model %v sent without IMAGE_MODEL set — must be omitted", gotBody["model"])
	}
}

func TestGenerateImageOpenAIError(t *testing.T) {
	clearImageEnv(t)

	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, `{"error":{"message":"model not loaded"}}`, http.StatusServiceUnavailable)
	}))
	defer srv.Close()
	t.Setenv("IMAGE_BASE_URL", srv.URL)

	_, err := GenerateImage("a lighthouse at dusk")
	if err == nil || !strings.Contains(err.Error(), "model not loaded") {
		t.Fatalf("err = %v, want API error surfacing the server message", err)
	}
}
